version: '3'

services:
  mysql:
    build: ./mysql/
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ../../sql:/tmp/sql
      - ./mysql/conf/custom.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
